import "oaidl.idl";

[uuid(AFF672AB-872C-402E-9152-E809ADC25CC7)]
library GraphQLService {
    importlib("stdole2.tlb");

    [
        object,
        nonextensible,
        local,
        pointer_default(unique),
        uuid(FA294686-DB83-4268-A84F-157012D56033),
        version(1.0),
        dual
    ]
    interface IGraphQLService : IDispatch {
        [id(1)] HRESULT fetchQuery([in] BSTR query, [in] BSTR operationName, [in] BSTR variables, [in] IDispatch* nextCallback, [out, retval] BSTR* result);
        [id(2)] HRESULT unsubscribe([in] INT key);
    };
}